-- UNOSI DRŽAVE
INSERT INTO DRŽAVE VALUES (DRZAVA_SEQ.NEXTVAL, 'Hrvatska');
INSERT INTO DRŽAVE VALUES (DRZAVA_SEQ.NEXTVAL, 'UK');
INSERT INTO DRŽAVE VALUES (DRZAVA_SEQ.NEXTVAL, 'SAD');
INSERT INTO DRŽAVE VALUES (DRZAVA_SEQ.NEXTVAL, 'Portugal');
INSERT INTO DRŽAVE VALUES (DRZAVA_SEQ.NEXTVAL, 'Egipat');
INSERT INTO DRŽAVE VALUES (DRZAVA_SEQ.NEXTVAL, 'Rusija');
INSERT INTO DRŽAVE VALUES (DRZAVA_SEQ.NEXTVAL, 'Kina');
INSERT INTO DRŽAVE VALUES (DRZAVA_SEQ.NEXTVAL, 'Brazil');
INSERT INTO DRŽAVE VALUES (DRZAVA_SEQ.NEXTVAL, 'Francuska');
INSERT INTO DRŽAVE VALUES (DRZAVA_SEQ.NEXTVAL, 'Njemaèka');
INSERT INTO DRŽAVE VALUES (DRZAVA_SEQ.NEXTVAL, 'Australija');
--SELECT * FROM DRŽAVE;


-- UNOSI DRŽAVE_KONTINENTI
-- Europa
INSERT INTO DRŽAVE_KONTINENTI VALUES (1, 1);
INSERT INTO DRŽAVE_KONTINENTI VALUES (3, 1);
INSERT INTO DRŽAVE_KONTINENTI VALUES (4, 1);
INSERT INTO DRŽAVE_KONTINENTI VALUES (6, 1);
INSERT INTO DRŽAVE_KONTINENTI VALUES (9, 1);
INSERT INTO DRŽAVE_KONTINENTI VALUES (10, 1);
-- S. Amerika
INSERT INTO DRŽAVE_KONTINENTI VALUES (12, 8);
-- J. Amerika
INSERT INTO DRŽAVE_KONTINENTI VALUES (8, 3);
-- Azija
INSERT INTO DRŽAVE_KONTINENTI VALUES (5, 4);
INSERT INTO DRŽAVE_KONTINENTI VALUES (6, 4);
INSERT INTO DRŽAVE_KONTINENTI VALUES (7, 4);
-- Australija
INSERT INTO DRŽAVE_KONTINENTI VALUES (11, 5);
--Afrika
INSERT INTO DRŽAVE_KONTINENTI VALUES (5, 6);
--SELECT * FROM DRŽAVE_KONTINENTI;


-- UNOSI FUNKCIJE_ZAPOSLENIKA
INSERT INTO FUNKCIJE_ZAPOSLENIKA VALUES (FUNKCIJA_ZAPOSLENIKA_SEQ.NEXTVAL, 'Menadžment', TO_DATE('02-02-2019','DD-MM-YYYY'), '');
INSERT INTO FUNKCIJE_ZAPOSLENIKA VALUES (FUNKCIJA_ZAPOSLENIKA_SEQ.NEXTVAL, 'Èišæenje', TO_DATE('19-01-2012','DD-MM-YYYY'), '');
INSERT INTO FUNKCIJE_ZAPOSLENIKA VALUES (FUNKCIJA_ZAPOSLENIKA_SEQ.NEXTVAL, 'IT', TO_DATE('31-01-2020','DD-MM-YYYY'), '');
INSERT INTO FUNKCIJE_ZAPOSLENIKA VALUES (FUNKCIJA_ZAPOSLENIKA_SEQ.NEXTVAL, 'IT', TO_DATE('16-07-2007','DD-MM-YYYY'), TO_DATE('18-08-2023','DD-MM-YYYY'));
INSERT INTO FUNKCIJE_ZAPOSLENIKA VALUES (FUNKCIJA_ZAPOSLENIKA_SEQ.NEXTVAL, 'IT', TO_DATE('12-01-2013','DD-MM-YYYY'), '');
INSERT INTO FUNKCIJE_ZAPOSLENIKA VALUES (FUNKCIJA_ZAPOSLENIKA_SEQ.NEXTVAL, 'IT', TO_DATE('28-11-2008','DD-MM-YYYY'), '');
INSERT INTO FUNKCIJE_ZAPOSLENIKA VALUES (FUNKCIJA_ZAPOSLENIKA_SEQ.NEXTVAL, 'Skladištarenje', TO_DATE('22-02-2002','DD-MM-YYYY'), TO_DATE('22-02-2019','DD-MM-YYYY'));
INSERT INTO FUNKCIJE_ZAPOSLENIKA VALUES (FUNKCIJA_ZAPOSLENIKA_SEQ.NEXTVAL, 'Skladištarenje', TO_DATE('20-05-2008','DD-MM-YYYY'), TO_DATE('22-05-2015','DD-MM-YYYY'));
INSERT INTO FUNKCIJE_ZAPOSLENIKA VALUES (FUNKCIJA_ZAPOSLENIKA_SEQ.NEXTVAL, 'Skladištarenje', TO_DATE('22-05-2022','DD-MM-YYYY'), '');
INSERT INTO FUNKCIJE_ZAPOSLENIKA VALUES (FUNKCIJA_ZAPOSLENIKA_SEQ.NEXTVAL, 'Skladištarenje', TO_DATE('22-05-2012','DD-MM-YYYY'), '');
INSERT INTO FUNKCIJE_ZAPOSLENIKA VALUES (FUNKCIJA_ZAPOSLENIKA_SEQ.NEXTVAL, 'Skladištarenje', TO_DATE('22-05-2012','DD-MM-YYYY'), TO_DATE('12-07-2029','DD-MM-YYYY'));
--SELECT * FROM FUNKCIJE_ZAPOSLENIKA;


-- UNOSI GRADOVI
INSERT INTO GRADOVI VALUES (GRAD_SEQ.NEXTVAL, '21000', 1, 'Split');
INSERT INTO GRADOVI VALUES (GRAD_SEQ.NEXTVAL, '10000', 1, 'Zagreb');
INSERT INTO GRADOVI VALUES (GRAD_SEQ.NEXTVAL, '23000', 1, 'Zadar');
INSERT INTO GRADOVI VALUES (GRAD_SEQ.NEXTVAL, '96850', 12, 'Honolulu');
INSERT INTO GRADOVI VALUES (GRAD_SEQ.NEXTVAL, '94110', 12, 'San Francisco');
INSERT INTO GRADOVI VALUES (GRAD_SEQ.NEXTVAL, '95959', 12, 'Nevada City');
INSERT INTO GRADOVI VALUES (GRAD_SEQ.NEXTVAL, '10001', 12, 'New York City');
INSERT INTO GRADOVI VALUES (GRAD_SEQ.NEXTVAL, '87101', 12, 'Albuquerque');
INSERT INTO GRADOVI VALUES (GRAD_SEQ.NEXTVAL, '', 5, 'Cairo');
INSERT INTO GRADOVI VALUES (GRAD_SEQ.NEXTVAL, '100000', 7, 'Beijing');
INSERT INTO GRADOVI VALUES (GRAD_SEQ.NEXTVAL, '', 6, 'Saint Petersburg');
INSERT INTO GRADOVI VALUES (GRAD_SEQ.NEXTVAL, '', 6, 'Moscow');
-- nema grada u UK i Portugalu unesenog
INSERT INTO GRADOVI VALUES (GRAD_SEQ.NEXTVAL, '14199', 10, 'Berlin');
INSERT INTO GRADOVI VALUES (GRAD_SEQ.NEXTVAL, '75116', 9, 'Pariz');
--SELECT * FROM GRADOVI;


-- UNOSI KATEGORIJE
INSERT INTO KATEGORIJE VALUES (KATEGORIJE_SEQ.NEXTVAL, 'Laptopi');
INSERT INTO KATEGORIJE VALUES (KATEGORIJE_SEQ.NEXTVAL, 'Miševi');
INSERT INTO KATEGORIJE VALUES (KATEGORIJE_SEQ.NEXTVAL, 'Tipkovnice');
INSERT INTO KATEGORIJE VALUES (KATEGORIJE_SEQ.NEXTVAL, 'Mobiteli');
INSERT INTO KATEGORIJE VALUES (KATEGORIJE_SEQ.NEXTVAL, 'Monitori');
INSERT INTO KATEGORIJE VALUES (KATEGORIJE_SEQ.NEXTVAL, 'CPU');
INSERT INTO KATEGORIJE VALUES (KATEGORIJE_SEQ.NEXTVAL, 'GPU');
--SELECT * FROM KATEGORIJE;


-- UNOSI KONTINENTI
INSERT INTO KONTINENTI VALUES (KONTINENT_SEQ.NEXTVAL, 'Europa');
INSERT INTO KONTINENTI VALUES (KONTINENT_SEQ.NEXTVAL, 'S. Amerika');
INSERT INTO KONTINENTI VALUES (KONTINENT_SEQ.NEXTVAL, 'J. Amerika');
INSERT INTO KONTINENTI VALUES (KONTINENT_SEQ.NEXTVAL, 'Azija');
INSERT INTO KONTINENTI VALUES (KONTINENT_SEQ.NEXTVAL, 'Australija');
INSERT INTO KONTINENTI VALUES (KONTINENT_SEQ.NEXTVAL, 'Afrika');
--SELECT * FROM KONTINENTI;


-- UNOSI KORISNICI
INSERT INTO KORISNICI VALUES (KORISNIK_SEQ.NEXTVAL, 200.02, '', 1, 'Ante', 'Antiæ', 'aantic@gmail.com', 'Maticeva 12', '123123123', TO_DATE('02-02-2002','DD-MM-YYYY'), 1);
INSERT INTO KORISNICI VALUES (KORISNIK_SEQ.NEXTVAL, 95.12, '', 5, 'Anthony', 'Smith', 'a.smith@gmail.com', 'Epic Alley 59', '345353454', TO_DATE('21-02-2002','DD-MM-YYYY'), 1);
INSERT INTO KORISNICI VALUES (KORISNIK_SEQ.NEXTVAL, 550.00, '', 5, 'Jeremiah', 'Jonnil', 'jerry@gmail.com', 'Jimmil Ave. 132', '546456565', TO_DATE('02-02-2002','DD-MM-YYYY'), 1);
INSERT INTO KORISNICI VALUES (KORISNIK_SEQ.NEXTVAL, 75.00, '2384932390', 9, 'Gustavo', 'Fring', 'gg@hotmail.com', 'Los Pollos 94', '678678678', TO_DATE('02-02-2002','DD-MM-YYYY'), 1);
INSERT INTO KORISNICI VALUES (KORISNIK_SEQ.NEXTVAL, 85.12, '3482057294', 14, 'Armani', 'Louise', 'ally@hotmail.com', 'Oui Oui 23', '798789789', TO_DATE('22-04-1992','DD-MM-YYYY'), 1);
INSERT INTO KORISNICI VALUES (KORISNIK_SEQ.NEXTVAL, 400.15, '', 8, 'Anna', 'Gunner', 'bbad@gmail.com', 'Breakfast 56', '789678567', TO_DATE('05-11-1985','DD-MM-YYYY'), 2);
INSERT INTO KORISNICI VALUES (KORISNIK_SEQ.NEXTVAL, 589.58, '', 12, 'Anna', 'Ivanova', 'avi@gmail.com', 'Ivljeva 222', '765345234', TO_DATE('01-01-2003','DD-MM-YYYY'), 2);
INSERT INTO KORISNICI VALUES (KORISNIK_SEQ.NEXTVAL, 122.12, '274659402', 10, 'Brenda', 'Reiner', 'brei@gmail.com', 'Neinenin 55', '344366878', TO_DATE('12-12-1999','DD-MM-YYYY'), 2);
INSERT INTO KORISNICI VALUES (KORISNIK_SEQ.NEXTVAL, 822.22, '', 7, 'Sasha', 'Mars', 'smasha@gmail.com', 'Buenonono 22', '123890089', TO_DATE('26-03-1977','DD-MM-YYYY'), 3);
INSERT INTO KORISNICI VALUES (KORISNIK_SEQ.NEXTVAL, 777.43, '837496028', 2, 'Rino', 'Tino', 'rintin@gmail.com', 'Marsova 123', '435345345', TO_DATE('02-12-2003','DD-MM-YYYY'), 3);
INSERT INTO KORISNICI VALUES (KORISNIK_SEQ.NEXTVAL, 777.43, '83749608', 2, 'Rno', 'Tno', 'rinin@gmail.com', 'Mars123', '4353345', TO_DATE('02-12-2003','DD-MM-YYYY'), 3);
--SELECT * FROM KORISNICI;


-- UNOSI KORISNICI_KATEGORIJE
-- za sluèaj da netko promijeni ime to bi se dalo riješiti triggerima
INSERT INTO KORISNICI_KATEGORIJE VALUES ('Dear Ante, the spring sale has begun!', 1, 1);
INSERT INTO KORISNICI_KATEGORIJE VALUES ('Dear Anthony, there is a 10% laptop discount!', 1, 2);
INSERT INTO KORISNICI_KATEGORIJE VALUES ('Dear Rino, there is a 10% laptop discount!', 1, 10);
INSERT INTO KORISNICI_KATEGORIJE VALUES ('Dear Gustavo, new laptops are here!', 1, 4);
INSERT INTO KORISNICI_KATEGORIJE VALUES ('Dear Anthony, the spring sale has begun!', 2, 2);
INSERT INTO KORISNICI_KATEGORIJE VALUES ('Dear Jeremiah, new mice are here!', 2, 3);
INSERT INTO KORISNICI_KATEGORIJE VALUES ('Dear Jeremiah, the spring sale has begun!', 3, 3);
INSERT INTO KORISNICI_KATEGORIJE VALUES ('Dear Jeremiah, the spring sale has begun!', 4, 3);
INSERT INTO KORISNICI_KATEGORIJE VALUES ('Dear Gustavo, the new Samsung Galaxy is here!', 4, 4);
INSERT INTO KORISNICI_KATEGORIJE VALUES ('Dear Armani, the new Samsung Galaxy is here!', 4, 5);
INSERT INTO KORISNICI_KATEGORIJE VALUES ('Dear Anna, there is a 25% phone discount!', 4, 6);
INSERT INTO KORISNICI_KATEGORIJE VALUES ('Dear Anna, the spring sale has begun!', 5, 6);
INSERT INTO KORISNICI_KATEGORIJE VALUES ('Dear Anna, the spring sale has begun!', 6, 7);
INSERT INTO KORISNICI_KATEGORIJE VALUES ('Dear Brenda, the spring sale has begun!', 7, 8);
INSERT INTO KORISNICI_KATEGORIJE VALUES ('Dear Sasha, more GPU-s are on their way!', 7, 9);
--SELECT * FROM KORISNICI_KATEGORIJE;


-- UNOSI PROIZVODI
INSERT INTO PROIZVODI VALUES (PROIZVOD_SEQ.NEXTVAL, 'SAMSUNG monitor', 'Spremni poraziti neprijatelje, bez zastoja ili zamuæenja.' , 179.99, 5);
INSERT INTO PROIZVODI VALUES (PROIZVOD_SEQ.NEXTVAL, 'LG 24MR400', 'Dijagonala zaslona 24.0, Rezolucija zaslona: 1920 x 1080, Omjer slike: 16:9' , 109.90, 5);
INSERT INTO PROIZVODI VALUES (PROIZVOD_SEQ.NEXTVAL, 'SAMSUNG GALAXY A54', 'Snimite svoje fantastiène trenutke s multikamerama.', 350.00, 4);
INSERT INTO PROIZVODI VALUES (PROIZVOD_SEQ.NEXTVAL, 'REDMI 12', 'Redmi 12 ima moæan MediaTek Helio G88 osmojezgreni procesor koji podržava osvježavanje od 90Hz.' , 179.00, 4);
INSERT INTO PROIZVODI VALUES (PROIZVOD_SEQ.NEXTVAL, 'ACER NX.KSJEX.00W', 'Ovaj lagani prijenosnik dolazi s elegantnim kuæištem i tankim okvirom zaslona.' , 519.50, 1);
INSERT INTO PROIZVODI VALUES (PROIZVOD_SEQ.NEXTVAL, 'ACER NX.KSJEX.008', 'Stvarajte. Igrajte. Radite. Uèite. Zabavite se.' , 720.00, 1);
INSERT INTO PROIZVODI VALUES (PROIZVOD_SEQ.NEXTVAL, 'ASUS E1504FA-BQ511', 'ASUS E Serija pruža lagan i kompaktan, novi moderan izgled za vaš dinamièan naèin života' , 512.00, 1);
INSERT INTO PROIZVODI VALUES (PROIZVOD_SEQ.NEXTVAL, 'ASUS B1502CBA-WB53C0', 'Ovaj vas neæe razoèarati.' , 999.00, 1);
INSERT INTO PROIZVODI VALUES (PROIZVOD_SEQ.NEXTVAL, 'HAMA 182602', 'Miš savršenog simetriènog oblika pogodan za lijevoruke i dešnjake' , 6.29, 2);
INSERT INTO PROIZVODI VALUES (PROIZVOD_SEQ.NEXTVAL, 'TRUST 24651', 'Iznimno tanka bežièna tipkovnica' , 22.00, 3);
INSERT INTO PROIZVODI VALUES (PROIZVOD_SEQ.NEXTVAL, 'Intel Core i5', 'Core i5 je generacija Intelovih procesora, izraðenih pomoæu x86-64 tehnologije.' , 125.00, 6);
-- nema GPU-a
--SELECT * FROM PROIZVODI;


-- UNOSI PROIZVODI_SKLADIŠTA
INSERT INTO PROIZVODI_SKLADIŠTA VALUES (9, 1, 20);
INSERT INTO PROIZVODI_SKLADIŠTA VALUES (4, 1, 12);
INSERT INTO PROIZVODI_SKLADIŠTA VALUES (12, 4, 133);
INSERT INTO PROIZVODI_SKLADIŠTA VALUES (13, 3, 45);
INSERT INTO PROIZVODI_SKLADIŠTA VALUES (2, 2, 34);
INSERT INTO PROIZVODI_SKLADIŠTA VALUES (4, 2, 21);
INSERT INTO PROIZVODI_SKLADIŠTA VALUES (14, 3, 22);
INSERT INTO PROIZVODI_SKLADIŠTA VALUES (3, 3, 10);
INSERT INTO PROIZVODI_SKLADIŠTA VALUES (3, 4, 9);
INSERT INTO PROIZVODI_SKLADIŠTA VALUES (6, 1, 2);
INSERT INTO PROIZVODI_SKLADIŠTA VALUES (2, 3, 23);
INSERT INTO PROIZVODI_SKLADIŠTA VALUES (8, 1, 45);
INSERT INTO PROIZVODI_SKLADIŠTA VALUES (10, 2, 75);
INSERT INTO PROIZVODI_SKLADIŠTA VALUES (11, 2, 23);
INSERT INTO PROIZVODI_SKLADIŠTA VALUES (11, 3, 21);
INSERT INTO PROIZVODI_SKLADIŠTA VALUES (11, 4, 27);
--SELECT * FROM PROIZVODI_SKLADIŠTA;


-- UNOSI RAÈUNI
INSERT INTO RAÈUNI VALUES (RACUN_SEQ.NEXTVAL, TO_DATE('02-02-2022','DD-MM-YYYY'), 'P', 1, 1, 3);
INSERT INTO RAÈUNI VALUES (RACUN_SEQ.NEXTVAL, TO_DATE('20-10-2023','DD-MM-YYYY'), 'P', 7, 5, 4);
INSERT INTO RAÈUNI VALUES (RACUN_SEQ.NEXTVAL, TO_DATE('23-06-2022','DD-MM-YYYY'), 'P', 3, 1, 5);
INSERT INTO RAÈUNI VALUES (RACUN_SEQ.NEXTVAL, TO_DATE('05-05-2020','DD-MM-YYYY'), 'P', 6, 2, 5);
INSERT INTO RAÈUNI VALUES (RACUN_SEQ.NEXTVAL, TO_DATE('06-07-2020','DD-MM-YYYY'), 'P', 6, 2, 5);
INSERT INTO RAÈUNI VALUES (RACUN_SEQ.NEXTVAL, TO_DATE('30-01-2019','DD-MM-YYYY'), 'K', 4, 4, 3);
INSERT INTO RAÈUNI VALUES (RACUN_SEQ.NEXTVAL, TO_DATE('22-02-2019','DD-MM-YYYY'), 'K', 5, 2, 4);
INSERT INTO RAÈUNI VALUES (RACUN_SEQ.NEXTVAL, TO_DATE('12-09-2017','DD-MM-YYYY'), 'K', 10, 1, 4);
--SELECT * FROM RAÈUNI;


-- UNOSI RAÈUNI_PROIZVODI
INSERT INTO RAÈUNI_PROIZVODI VALUES (STAVKA_SEQ.NEXTVAL, 2, 13, 5);
INSERT INTO RAÈUNI_PROIZVODI VALUES (STAVKA_SEQ.NEXTVAL, 1, 2, 4);
INSERT INTO RAÈUNI_PROIZVODI VALUES (STAVKA_SEQ.NEXTVAL, 1, 2, 4);
INSERT INTO RAÈUNI_PROIZVODI VALUES (STAVKA_SEQ.NEXTVAL, 2, 4, 4);
INSERT INTO RAÈUNI_PROIZVODI VALUES (STAVKA_SEQ.NEXTVAL, 3, 14, 7);
INSERT INTO RAÈUNI_PROIZVODI VALUES (STAVKA_SEQ.NEXTVAL, 5, 12, 3);
INSERT INTO RAÈUNI_PROIZVODI VALUES (STAVKA_SEQ.NEXTVAL, 1, 8, 5);
INSERT INTO RAÈUNI_PROIZVODI VALUES (STAVKA_SEQ.NEXTVAL, 1, 9, 5);
INSERT INTO RAÈUNI_PROIZVODI VALUES (STAVKA_SEQ.NEXTVAL, 4, 2, 6);
INSERT INTO RAÈUNI_PROIZVODI VALUES (STAVKA_SEQ.NEXTVAL, 2, 8, 8);
INSERT INTO RAÈUNI_PROIZVODI VALUES (STAVKA_SEQ.NEXTVAL, 2, 14, 9);
INSERT INTO RAÈUNI_PROIZVODI VALUES (STAVKA_SEQ.NEXTVAL, 2, 2, 10);
--SELECT * FROM RAÈUNI_PROIZVODI;


-- UNOSI SKLADIŠTA
INSERT INTO SKLADIŠTA VALUES (SKLADISTE_SEQ.NEXTVAL, 'Antiæeva 12', 1);
INSERT INTO SKLADIŠTA VALUES (SKLADISTE_SEQ.NEXTVAL, 'Louiseva 24', 14);
INSERT INTO SKLADIŠTA VALUES (SKLADISTE_SEQ.NEXTVAL, 'Jon Garfield 99', 5);
INSERT INTO SKLADIŠTA VALUES (SKLADISTE_SEQ.NEXTVAL, 'Xinyan 22', 10);
--SELECT * FROM SKLADIŠTA;


-- UNOSI SPOLOVI
INSERT INTO SPOLOVI VALUES (SPOL_SEQ.NEXTVAL, 'Muško', 'M');
INSERT INTO SPOLOVI VALUES (SPOL_SEQ.NEXTVAL, 'Žensko', 'Ž');
INSERT INTO SPOLOVI VALUES (SPOL_SEQ.NEXTVAL, 'Ostalo', '');
--SELECT * FROM SPOLOVI;


-- UNOSI VALUTE
INSERT INTO VALUTE VALUES (VALUTA_SEQ.NEXTVAL, 'Euro');
INSERT INTO VALUTE VALUES (VALUTA_SEQ.NEXTVAL, 'USD');
INSERT INTO VALUTE VALUES (VALUTA_SEQ.NEXTVAL, 'AUD');
INSERT INTO VALUTE VALUES (VALUTA_SEQ.NEXTVAL, 'Yuan');
INSERT INTO VALUTE VALUES (VALUTA_SEQ.NEXTVAL, 'R. rubalj');
INSERT INTO VALUTE VALUES (VALUTA_SEQ.NEXTVAL, 'Funte');
--SELECT * FROM VALUTE;


-- UNOSI ZAPOSLENICI
-- Menadžer
INSERT INTO ZAPOSLENICI VALUES (ZAPOSLENIK_SEQ.NEXTVAL, 4, 1, 6, 'Johnny', 'Cage', 'johnnyc@gmail.com', 'Skibidi 14', '204839562', TO_DATE('02-02-1992','DD-MM-YYYY'), 1, 3000.00);
-- Èistaèi
INSERT INTO ZAPOSLENICI VALUES (ZAPOSLENIK_SEQ.NEXTVAL, 5, 1, 1, 'Siniša', 'Sinko', 'sinisa@gmail.com', 'Marka Maruliæa 13', '203122839', TO_DATE('02-02-1964','DD-MM-YYYY'), 3, 1200.50);
-- IT
INSERT INTO ZAPOSLENICI VALUES (ZAPOSLENIK_SEQ.NEXTVAL, 6, 1, 11, 'Ivan', 'Drago', 'rocky@gmail.com', 'Beljeljeva 52', '039372644', TO_DATE('12-04-1998','DD-MM-YYYY'), 1, 2000.00);
INSERT INTO ZAPOSLENICI VALUES (ZAPOSLENIK_SEQ.NEXTVAL, 9, 2, 1, 'Antonija', 'Aniæ', 'ani@gmail.com', 'Marka Maruliæa 14', '101013832', TO_DATE('05-06-1992','DD-MM-YYYY'), 2, 1910.10);
INSERT INTO ZAPOSLENICI VALUES (ZAPOSLENIK_SEQ.NEXTVAL, 10, 3, 5, 'Diego', 'Muniz', 'dim@gmail.com', 'Gutierrez 66', '444854732', TO_DATE('02-12-1982','DD-MM-YYYY'), 1, 1910.10);
-- Skladištari
INSERT INTO ZAPOSLENICI VALUES (ZAPOSLENIK_SEQ.NEXTVAL, 13, 3, 5, 'Dora', 'Eksplora', 'dddora@gmail.com', 'Don Quijote 14', '039383022', TO_DATE('04-11-1973','DD-MM-YYYY'), 2, 1500.00);
INSERT INTO ZAPOSLENICI VALUES (ZAPOSLENIK_SEQ.NEXTVAL, 14, 3, 4, 'Duje', 'Svetac', 'sv.duje@hotmail.com', 'Crkvena 1', '111829444', TO_DATE('28-11-1978','DD-MM-YYYY'), 1, 1600.00);
INSERT INTO ZAPOSLENICI VALUES (ZAPOSLENIK_SEQ.NEXTVAL, 15, 4, 13, 'Patrik', 'Zvijezda', 'bikbot@gmail.com', 'Alge 3', '938467194', TO_DATE('01-01-1968','DD-MM-YYYY'), 3, 1555.55);
--SELECT * FROM ZAPOSLENICI;

--------------------------------------------------------------------------------------------------------------------------------

--UPDATE ZAPOSLENICI
--SET ADRESA = 'Marka Maruliæa 15'
--WHERE ID_ZAPOSLENIK = 4;

--------------------------------------------------------------------------------------------------------------------------------

--DELETE
--FROM KORISNICI
--WHERE ID_KORISNIK = 12;

--------------------------------------------------------------------------------------------------------------------------------

--1. SELECT UPIT
--Menadžer web trgovine traži izvještaj o pregledu inventara. 
--Traže se podaci o ukupnoj vrijednosti (u eurima) i kolièini proizvoda u inventaru svakog pojedinog skladišta,
--te gdje se uopæe nalazi to skladište (grad i država).
--Izvještaj, to jest tablica mora biti poredana, odnosno sortirana, silazno, po vrijednosti unutar skladišta.
SELECT 
D."NAZIV_DRŽAVE" AS "NAZIV DRŽAVE",
G."NAZIV_GRADA" AS "NAZIV GRADA",
S."ADRESA_SKLADIŠTA" AS "ADRESA SKLADIŠTA",
SUM(PS."KOLIÈINA") AS "UKUPNA KOLIÈINA",
SUM(P.CIJENA * PS."KOLIÈINA") || ' ' || 'eura' AS "UKUPNA VRIJEDNOST"
FROM "SKLADIŠTA" S
INNER JOIN GRADOVI G ON G.ID_GRAD = S.GRADOVI_ID_GRAD
INNER JOIN "DRŽAVE" D ON D."ID_DRŽAVE" = G."DRŽAVE_ID_DRŽAVE"
INNER JOIN "PROIZVODI_SKLADIŠTA" PS ON PS."SKLADIŠTA_ID_SKLADIŠTE" = S."ID_SKLADIŠTE"
INNER JOIN PROIZVODI P ON P.ID_PROIZVOD = PS."PROIZVODI_ID_PROIZVOD"
GROUP BY D."NAZIV_DRŽAVE", G."NAZIV_GRADA", S."ADRESA_SKLADIŠTA"
ORDER BY 5 DESC;

--2. SELECT UPIT
--Web trgovina pokušava održati nagradnu igru koja se temelji na principu lutrije.
--Izvlaèe se kuglice sa razlièitim obilježjima, te oni korisnici koji zadovoljavaju sva ta obilježja dobivaju (još neodreðenu) nagradu.
--Nakon izvlaèenja kuglica, dobivena obilježja korisnika moraju biti sljedeæa: 
--korisnik ne smije biti oznaèen na profilu kao muškarac, i njihovo ime i njihovo prezime moraju sadržavati slovo "n", trebali su ukupno potrošiti više od 100, a manje od 600 eura na web trgovini,
--te njihov OIB (odnosno jedinstven identifikator) mora sadržavati broj "78" i još mora vrijediti da su roðeni u prošlom tisuæljeæu.
--Traži se prikaz svih korisnika koji zadovoljavaju ova obilježja, toènije:
--njihovo ime i prezime, jedinstveni "OIB" tih korisnika, datum roðenja, njihov spol, te koliko su ukupno potrošili novca na web trgovini.
SELECT
K.IME || ' ' || K.PREZIME AS "IME I PREZIME",
K.OIB,
K."DATUM_ROÐENJA" AS "DATUM ROÐENJA",
S.NAZIV_SPOLA AS "SPOL",
K."UKUPNO_PLAÆENO" AS "UKUPNO POTROŠENO"
FROM KORISNICI K
INNER JOIN SPOLOVI S ON S.ID_SPOL = K.SPOLOVI_ID_SPOL
WHERE K.SPOLOVI_ID_SPOL != 1
AND (K.IME LIKE '%N%' OR K.IME LIKE '%n%')
AND (K.PREZIME LIKE '%N%' OR K.PREZIME LIKE '%n%')
AND K."UKUPNO_PLAÆENO" IN (
  SELECT DISTINCT K."UKUPNO_PLAÆENO"
  FROM KORISNICI K
  WHERE K."UKUPNO_PLAÆENO" > 100 AND K."UKUPNO_PLAÆENO" < 600
)AND K.OIB LIKE '%78%'
AND EXTRACT(YEAR FROM K."DATUM_ROÐENJA") <= 2000;

--3. SELECT UPIT
--Menadžera web trgovine zanimaju odreðene informacije vezane uz trajanje ugovora svakog trenutnog i/ili bivšeg zaposlenika.
--Znaèi, potreban nam je ispis (prikazanog kao entitet) na kojem æemo saznati, kao prvo,
--o kojim se zaposlenicima radi, ako još uvijek rade(tj. traže se osnovni osobni podaci, tj. ime, prezime, OIB, spol, te datum i mjesto roðenja) ili upisati "Obrisano" ako više nemaju te podatke sadržane u bazi podataka,
--treba nam i njihova trenutna, odnosno bivša funkcija u radu za web trgovinu, te od kad, (pa i eventualno do kad) su izvršavali tu funkciju, s tim da ako im istek ugovora nije odreðen onda to trebamo i naznaèiti
--, takoðer odmah do tog podatka je željen taj isti podatak, no prikazan u formatu broja dana rada za web trgovinu radi lakšeg išèitavanja.
--Sve ove podatke, radi boljeg pregleda, sortirati silazno po broju dana rada za web trgovinu.
SELECT 
COALESCE(NULLIF(Z.IME || ' ' || Z.PREZIME, ' '), 'Obrisano') AS "IME I PREZIME",
COALESCE(Z.OIB, 'Obrisano') AS OIB,
COALESCE(S.NAZIV_SPOLA, 'Obrisano') AS "SPOL",
COALESCE(TO_CHAR(Z."DATUM_ROÐENJA"), 'Obrisano') AS "DATUM ROÐENJA",
COALESCE(G.NAZIV_GRADA, 'Obrisano') AS "MJESTO ROÐENJA",
F.NAZIV_FUNKCIJE AS "FUNKCIJA",
F.OD_KAD as "POÈETAK UGOVORA",
COALESCE(TO_CHAR(F.DO_KAD), 'Neodreðeno') AS "KRAJ UGOVORA",
COALESCE(F.DO_KAD - F.OD_KAD, TRUNC(SYSDATE) - F.OD_KAD) || ' ' || 'dan(a)' AS "BROJ DANA RADA"
FROM ZAPOSLENICI Z
RIGHT JOIN FUNKCIJE_ZAPOSLENIKA F ON F.ID_FUNKCIJA_ZAPOSLENIKA = Z.FUNKCIJE_ZAPOSLENIKA_ID2
LEFT JOIN SPOLOVI S ON S.ID_SPOL = Z.SPOLOVI_ID_SPOL
LEFT JOIN GRADOVI G ON G.ID_GRAD = Z.GRADOVI_ID_GRAD
ORDER BY COALESCE(F.DO_KAD - F.OD_KAD, TRUNC(SYSDATE) - F.OD_KAD) DESC;

--4. SELECT UPIT
--Potrebna nam je detaljna analiza svih digitalnih raèuna koje smo izdali poslije 2018. godine.
--Trebamo prikazati prezime i ime (u formatu "prezime, ime") svakog izdavatelja raèuna i korisnika poslije te godine.
--Uz korisnika je potreban i njihov "OIB", odnosno jedinstven numerièki identifikator. Takoðer nam je bitno da toèno saznamo kontinent i državu u kojoj se korisnik nalazi,
--te poštanski broj na koji su poslani ti proizvodi, ako je korisnik na raèunu uopæe dao poštanski broj. Ako nije to trebamo u prikazu istaknuti.
--Potrebna nam je i informacija o tome koliko je kupac potrošio na pojedinu stavku raèuna, koliko su pojedinog proizvoda kupili,
--u koju kategoriju spadaju ti proizvodi, te iz kojeg su skladišta došli. Takoðer, potreban nam je i datyum same kupnje.
--Bitno je i na koji je naèin izvedena sama kupnja (pouzeæem ili karticom), potrebno je ispisati broj kartice ako ju je korisnik dao.
--Prikaz sortirati po datumu kupnje, pa po prezimenima kupaca.
SELECT 
Z.PREZIME || ', ' || Z.IME AS "PREZIME, IME IZDAVAÈA",
K.PREZIME || ', ' || K.IME AS "PREZIME, IME KUPCA",
K.OIB AS "OIB KUPCA",
KON.NAZIV_KONTINENTA AS "KONTINENT KUPCA",
D."NAZIV_DRŽAVE" AS "DRŽAVA KUPCA",
COALESCE(G."POŠTANSKI_BROJ", 'Nema podatka') AS "POŠTANSKI BROJ KUPCA",
S."ADRESA_SKLADIŠTA" AS "ADRESA SKLADIŠTA",
KAT.NAZIV_KATEGORIJE AS "KATEGORIJA PROIZVODA",
P.NAZIV_PROIZVODA AS "STAVKA RAÈUNA",
RP.KOLIÈINA AS "KOLIÈINA KUPLJENA",
R.DATUM_KUPNJE AS "DATUM KUPNJE",
CASE
  WHEN R."NAÈIN_PLAÆANJA" = 'K' THEN 'Karticom'
  ELSE 'Pouzeæem'
END AS "NAÈIN PLAÆANJA",
COALESCE(K.KARTICA, 'Nema podatka') AS "KARTICA KUPCA"
FROM "RAÈUNI" R
INNER JOIN "RAÈUNI_PROIZVODI" RP ON RP."RAÈUNI_ID_RAÈUNI" = R."ID_RAÈUNI"
INNER JOIN ZAPOSLENICI Z ON Z.ID_ZAPOSLENIK = R.ZAPOSLENICI_ID_ZAPOSLENIK
INNER JOIN KORISNICI K ON K.ID_KORISNIK = R.KORISNICI_ID_KORISNIK
INNER JOIN GRADOVI G ON G.ID_GRAD = K.GRADOVI_ID_GRAD
INNER JOIN "DRŽAVE" D ON D."ID_DRŽAVE" = G."DRŽAVE_ID_DRŽAVE"
INNER JOIN "DRŽAVE_KONTINENTI" DK ON DK."DRŽAVE_ID_DRŽAVE" = D."ID_DRŽAVE"
INNER JOIN KONTINENTI KON ON KON.ID_KONTINENTI = DK.KONTINENTI_ID_KONTINENTI
INNER JOIN PROIZVODI P ON P.ID_PROIZVOD = RP.PROIZVODI_ID_PROIZVOD
INNER JOIN "PROIZVODI_SKLADIŠTA" PS ON PS.PROIZVODI_ID_PROIZVOD = P.ID_PROIZVOD
INNER JOIN "SKLADIŠTA" S ON S."ID_SKLADIŠTE" = PS."SKLADIŠTA_ID_SKLADIŠTE"
INNER JOIN KATEGORIJE KAT ON KAT.ID_KATEGORIJE = P.KATEGORIJE_ID_KATEGORIJE
WHERE EXTRACT(YEAR FROM R.DATUM_KUPNJE) > 2018
ORDER BY 11, 2;